# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Episodios
    url: '#posts'
    weight: 20
  - name: Sobre epiSTEMas
    url: '#about'
    weight: 30
  - name: Noticias
    url: '#featured'
    weight: 40
  - name: Anfitrionas
    url: '#projects'
    weight: 50
  - name: Membresías
    url: '#members'
    weight: 60
  - name: Temas
    url: '#tags'
    weight: 70
  - name: Contáctanos
    url: '#contact'
    weight: 80
